name: 部署

on:
  workflow_dispatch:
  push:
    branches:
      - 'latest'

concurrency:
  group: '部署'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取本仓库
        uses: actions/checkout@v4

      - name: 安装 mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.37'
          # mdbook-version: 'latest'

      - name: 构建
        run: bash ./build.bash

      # HTML/CSS/JS Minifier
      # - uses: docker://devatherock/minify-js:2.0.0
      #   with:
      #     add_suffix: false     # Optional
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./build/**

      - name: 部署
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./build --project-name=wedot-docs
